# Generated by Django 5.2.3 on 2025-06-27 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('state_of_origin', models.CharField(max_length=100)),
                ('lga', models.CharField(max_length=100)),
                ('membership_no', models.CharField(max_length=20, unique=True)),
                ('passport_photo', models.ImageField(blank=True, null=True, upload_to='passports/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
