# Generated by Django 5.2.3 on 2025-06-27 15:28

import form.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='passport_photo',
            field=models.ImageField(default=form.models.get_default_passport, upload_to='passports/'),
        ),
    ]
