# Generated by Django 5.2.3 on 2025-06-28 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0004_alter_member_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='phone',
            field=models.CharField(max_length=20, null=True, verbose_name='Phone Number'),
        ),
    ]
